version: "3.1"

services:
  myrestapi:
    build: .
    image: myrestapi:latest
    ports:
      - "8080:80"

  # postgres:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: rpg-api-db
  #   ports:
  #     - "5432:5432"
